apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.workload.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    # Workload Identity — binds this KSA to the GCP SA provisioned in Terraform
    iam.gke.io/gcp-service-account: nexus-workload@{{ .Values.global.gcpProjectId }}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.cloudSqlProxy.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: nexus-cloudsql-proxy@{{ .Values.global.gcpProjectId }}.iam.gserviceaccount.com
